require('samuele.plugins-setup')
require('samuele.core.options')
require('samuele.core.keymaps')
require('samuele.core.colorscheme')
require('samuele.plugins.comment')
require('samuele.plugins.nvim-tree')
require('samuele.plugins.lualine')
-- require('samuele.core.statusline')
require('samuele.plugins.telescope')
require('samuele.plugins.nvim-cmp')
require('samuele.plugins.lsp.mason')
require('samuele.plugins.lsp.lspsaga')
require('samuele.plugins.lsp.lspconfig')

